# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johannes Leander
email: johleander@gmail.com
description: Johannes Leander is a software engineer with focus on UI/UX and Data Visualization. He holds a M.Sc. in Media Technology and likes to create intuitive and informative products. He is also interested in flags, their history and symbolism. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johannesleander.com" # the base hostname & protocol for your site
twitter_username: johleander
github_username:  johleander

# Build settings
markdown: kramdown
kramdown:
  input: GFM


#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->
